import { UserProfile, SocialFeedPost, StoryItem, ChatRoom, ChatMessage } from '../types/chat';

export const DUMMY_USERS: UserProfile[] = [
  {
    id: 'user_tanvir_ahmed',
    name: 'Tanvir Ahmed',
    username: 'tanvir_ahmed',
    email: 'tanvir@simi.app',
    gender: 'male',
    avatarId: 'falcon',
    customAvatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    coverUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&auto=format&fit=crop&q=80',
    bio: 'Photographer & travel enthusiast 📷 Living life one sunset at a time.',
    location: 'Sylhet, Bangladesh',
    joinedDate: 'Joined Jan 2024',
    moodEmoji: '✨',
    moodText: 'Chasing golden hour',
    theme: 'midnight',
    status: 'online',
    showActiveStatus: true,
    badge: 'Verified Member',
    soundEnabled: true,
    createdAt: Date.now() - 90 * 24 * 60 * 60 * 1000,
    lastSeen: Date.now() - 2 * 60 * 1000,
    buddyIds: ['user_mira_vibe', 'user_arif_hasan', 'user_nusrat_jahan'],
  },
  {
    id: 'user_mira_vibe',
    name: 'Mira',
    username: 'mira_vibe',
    email: 'mira@simi.app',
    gender: 'female',
    avatarId: 'bunny',
    customAvatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
    coverUrl: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=1200&auto=format&fit=crop&q=80',
    bio: 'Creative soul 🎨 Coffee lover ☕ Finding magic in everyday moments ✨',
    location: 'Dhaka, Bangladesh',
    joinedDate: 'Joined Feb 2024',
    moodEmoji: '🌸',
    moodText: 'Painting & sipping matcha',
    theme: 'strawberry',
    status: 'online',
    showActiveStatus: true,
    badge: 'VIP Member',
    soundEnabled: true,
    createdAt: Date.now() - 75 * 24 * 60 * 60 * 1000,
    lastSeen: Date.now() - 1 * 60 * 1000,
    buddyIds: ['user_tanvir_ahmed', 'user_nusrat_jahan', 'user_sadia_islam'],
  },
  {
    id: 'user_arif_hasan',
    name: 'Arif Hasan',
    username: 'arif_hasan',
    email: 'arif@simi.app',
    gender: 'male',
    avatarId: 'wolf',
    customAvatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    coverUrl: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=1200&auto=format&fit=crop&q=80',
    bio: 'Tech geek & UI enthusiast 💻 Always up for great conversations & coffee.',
    location: 'Chittagong, Bangladesh',
    joinedDate: 'Joined Mar 2024',
    moodEmoji: '🔥',
    moodText: 'Coding mode on',
    theme: 'midnight',
    status: 'online',
    showActiveStatus: true,
    badge: 'Pro Member',
    soundEnabled: true,
    createdAt: Date.now() - 60 * 24 * 60 * 60 * 1000,
    lastSeen: Date.now() - 5 * 60 * 1000,
    buddyIds: ['user_tanvir_ahmed', 'user_pranto_das'],
  },
  {
    id: 'user_nusrat_jahan',
    name: 'Nusrat Jahan',
    username: 'nusrat_jahan',
    email: 'nusrat@simi.app',
    gender: 'female',
    avatarId: 'kitten',
    customAvatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    coverUrl: 'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1200&auto=format&fit=crop&q=80',
    bio: 'Wanderlust & nature explorer 🌿 Capturing smiles, skies and mountain mists.',
    location: 'Rajshahi, Bangladesh',
    joinedDate: 'Joined Jan 2024',
    moodEmoji: '💖',
    moodText: 'Weekend getaway',
    theme: 'lavender',
    status: 'online',
    showActiveStatus: true,
    badge: 'Verified Member',
    soundEnabled: true,
    createdAt: Date.now() - 80 * 24 * 60 * 60 * 1000,
    lastSeen: Date.now() - 10 * 60 * 1000,
    buddyIds: ['user_mira_vibe', 'user_sadia_islam'],
  },
  {
    id: 'user_sadia_islam',
    name: 'Sadia Islam',
    username: 'sadia07',
    email: 'sadia@simi.app',
    gender: 'female',
    avatarId: 'panda',
    customAvatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    coverUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80',
    bio: 'Life is short, make every moment count 💫 Fashion, design & sunset lover.',
    location: 'Dhaka, Bangladesh',
    joinedDate: 'Joined Apr 2024',
    moodEmoji: '🎀',
    moodText: 'Feeling inspired',
    theme: 'strawberry',
    status: 'online',
    showActiveStatus: true,
    badge: 'Active Member',
    soundEnabled: true,
    createdAt: Date.now() - 50 * 24 * 60 * 60 * 1000,
    lastSeen: Date.now() - 15 * 60 * 1000,
    buddyIds: ['user_mira_vibe', 'user_nusrat_jahan'],
  },
  {
    id: 'user_pranto_das',
    name: 'Pranto Das',
    username: 'pranto01',
    email: 'pranto@simi.app',
    gender: 'male',
    avatarId: 'bear',
    customAvatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80',
    coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&auto=format&fit=crop&q=80',
    bio: 'Music, acoustic sessions & late night thoughts 🎸 Audio engineer.',
    location: 'Khulna, Bangladesh',
    joinedDate: 'Joined May 2024',
    moodEmoji: '🎧',
    moodText: 'In the zone',
    theme: 'midnight',
    status: 'idle',
    showActiveStatus: true,
    badge: 'Community Contributor',
    soundEnabled: true,
    createdAt: Date.now() - 40 * 24 * 60 * 60 * 1000,
    lastSeen: Date.now() - 30 * 60 * 1000,
    buddyIds: ['user_arif_hasan'],
  },
  {
    id: 'user_rimjhim',
    name: 'Rimjhim',
    username: 'rim_22',
    email: 'rimjhim@simi.app',
    gender: 'female',
    avatarId: 'fox',
    customAvatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&auto=format&fit=crop&q=80',
    coverUrl: 'https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?w=1200&auto=format&fit=crop&q=80',
    bio: 'Rain lover 🌧️ Books, poetry and warm chai ☕ Finding calm in chaos.',
    location: 'Sylhet, Bangladesh',
    joinedDate: 'Joined Jun 2024',
    moodEmoji: '☕',
    moodText: 'Reading cozy novels',
    theme: 'matcha',
    status: 'online',
    showActiveStatus: true,
    badge: 'Early Adopter',
    soundEnabled: true,
    createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000,
    lastSeen: Date.now() - 8 * 60 * 1000,
    buddyIds: ['user_mira_vibe'],
  },
  {
    id: 'user_faria_khan',
    name: 'Faria Khan',
    username: 'faria.k',
    email: 'faria@simi.app',
    gender: 'female',
    avatarId: 'puppy',
    customAvatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
    coverUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&auto=format&fit=crop&q=80',
    bio: 'Architect in making 📐 Simplicity is the ultimate sophistication.',
    location: 'Dhaka, Bangladesh',
    joinedDate: 'Joined Jul 2024',
    moodEmoji: '🏛️',
    moodText: 'Drafting new sketches',
    theme: 'sky',
    status: 'offline',
    showActiveStatus: true,
    badge: 'Pro Member',
    soundEnabled: true,
    createdAt: Date.now() - 20 * 24 * 60 * 60 * 1000,
    lastSeen: Date.now() - 3 * 3600 * 1000,
    buddyIds: ['user_sadia_islam'],
  },
];

export const DUMMY_FEED_POSTS: SocialFeedPost[] = [
  {
    id: 'post_tanvir_1',
    authorId: 'user_tanvir_ahmed',
    authorName: 'Tanvir Ahmed',
    authorAvatar: 'falcon',
    authorCustomAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    createdAt: Date.now() - 2 * 3600 * 1000,
    timeAgo: '2h ago',
    location: 'Yosemite Valley',
    isPublic: true,
    content: 'Sometimes the right people make ordinary places feel extraordinary ✨',
    images: [
      'https://images.unsplash.com/photo-1426604966848-d7adac402bff?w=900&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=900&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?w=900&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=900&auto=format&fit=crop&q=80',
    ],
    likes: 1240,
    commentsCount: 86,
    sharesCount: 42,
    isLiked: false,
    isSaved: false,
  },
  {
    id: 'post_mira_1',
    authorId: 'user_mira_vibe',
    authorName: 'Mira',
    authorAvatar: 'bunny',
    authorCustomAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
    createdAt: Date.now() - 4 * 3600 * 1000,
    timeAgo: '4h ago',
    location: 'Dhanmondi Lake',
    isPublic: true,
    content: 'Chasing sunsets and pretty skies 🌅 Today was peaceful and full of warmth.',
    images: [
      'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=900&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=900&auto=format&fit=crop&q=80',
    ],
    likes: 945,
    commentsCount: 62,
    sharesCount: 18,
    isLiked: false,
    isSaved: false,
  },
  {
    id: 'post_arif_1',
    authorId: 'user_arif_hasan',
    authorName: 'Arif Hasan',
    authorAvatar: 'wolf',
    authorCustomAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    createdAt: Date.now() - 6 * 3600 * 1000,
    timeAgo: '6h ago',
    location: 'Gulshan 2',
    isPublic: true,
    content: 'Weekend hackathon vibes ☕💻 Built a real-time messaging engine with WebRTC!',
    images: [
      'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=900&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=900&auto=format&fit=crop&q=80',
    ],
    likes: 632,
    commentsCount: 39,
    sharesCount: 14,
    isLiked: false,
    isSaved: false,
  },
  {
    id: 'post_nusrat_1',
    authorId: 'user_nusrat_jahan',
    authorName: 'Nusrat Jahan',
    authorAvatar: 'kitten',
    authorCustomAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    createdAt: Date.now() - 8 * 3600 * 1000,
    timeAgo: '8h ago',
    location: 'Sajek Valley',
    isPublic: true,
    content: 'A breath of fresh mountain air 🍃 Nature always heals what words cannot.',
    images: [
      'https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=900&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=900&auto=format&fit=crop&q=80',
    ],
    likes: 812,
    commentsCount: 51,
    sharesCount: 22,
    isLiked: false,
    isSaved: false,
  },
  {
    id: 'post_sadia_1',
    authorId: 'user_sadia_islam',
    authorName: 'Sadia Islam',
    authorAvatar: 'panda',
    authorCustomAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    createdAt: Date.now() - 24 * 3600 * 1000,
    timeAgo: '1d ago',
    location: "Cox's Bazar",
    isPublic: true,
    content: 'Ocean breeze and golden rays 🌊 Living for quiet moments like these.',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=900&auto=format&fit=crop&q=80',
    ],
    likes: 754,
    commentsCount: 44,
    sharesCount: 16,
    isLiked: false,
    isSaved: false,
  },
];

export const DUMMY_STORIES: StoryItem[] = [
  {
    id: 'story_tanvir',
    userId: 'user_tanvir_ahmed',
    userName: 'Tanvir Ahmed',
    userAvatar: 'falcon',
    userCustomAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=900&auto=format&fit=crop&q=80',
    text: 'Sunrise over the ridge 🌄',
    createdAt: Date.now() - 3 * 3600 * 1000,
    expiresAt: Date.now() + 21 * 3600 * 1000,
    viewers: [],
    reactions: {},
  },
  {
    id: 'story_mira',
    userId: 'user_mira_vibe',
    userName: 'Mira',
    userAvatar: 'bunny',
    userCustomAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=900&auto=format&fit=crop&q=80',
    text: 'Morning warmth & latte art ☕✨',
    createdAt: Date.now() - 4 * 3600 * 1000,
    expiresAt: Date.now() + 20 * 3600 * 1000,
    viewers: [],
    reactions: {},
  },
  {
    id: 'story_arif',
    userId: 'user_arif_hasan',
    userName: 'Arif Hasan',
    userAvatar: 'wolf',
    userCustomAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=900&auto=format&fit=crop&q=80',
    text: 'New feature deployed 🚀',
    createdAt: Date.now() - 5 * 3600 * 1000,
    expiresAt: Date.now() + 19 * 3600 * 1000,
    viewers: [],
    reactions: {},
  },
  {
    id: 'story_nusrat',
    userId: 'user_nusrat_jahan',
    userName: 'Nusrat Jahan',
    userAvatar: 'kitten',
    userCustomAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=900&auto=format&fit=crop&q=80',
    text: 'Valley of clouds ☁️',
    createdAt: Date.now() - 6 * 3600 * 1000,
    expiresAt: Date.now() + 18 * 3600 * 1000,
    viewers: [],
    reactions: {},
  },
  {
    id: 'story_sadia',
    userId: 'user_sadia_islam',
    userName: 'Sadia Islam',
    userAvatar: 'panda',
    userCustomAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=900&auto=format&fit=crop&q=80',
    text: 'Golden waves 🌊',
    createdAt: Date.now() - 7 * 3600 * 1000,
    expiresAt: Date.now() + 17 * 3600 * 1000,
    viewers: [],
    reactions: {},
  },
];

export const createDummyDirectRooms = (currentUserId: string): ChatRoom[] => {
  return [
    {
      id: `direct_${currentUserId}_user_mira_vibe`,
      name: 'Mira',
      description: 'Direct Message',
      icon: '💬',
      type: 'direct',
      isDirect: true,
      participantIds: [currentUserId, 'user_mira_vibe'],
      unreadCount: 2,
      lastMessage: 'Let\'s catch up soon! 🌸',
      lastMessageTime: Date.now() - 9 * 60 * 1000,
      createdAt: Date.now() - 10 * 24 * 3600 * 1000,
    },
    {
      id: `direct_${currentUserId}_user_arif_hasan`,
      name: 'Arif Hasan',
      description: 'Direct Message',
      icon: '💬',
      type: 'direct',
      isDirect: true,
      participantIds: [currentUserId, 'user_arif_hasan'],
      unreadCount: 1,
      lastMessage: 'Let\'s catch up tomorrow! 🔥',
      lastMessageTime: Date.now() - 40 * 60 * 1000,
      createdAt: Date.now() - 8 * 24 * 3600 * 1000,
    },
    {
      id: `direct_${currentUserId}_user_nusrat_jahan`,
      name: 'Nusrat Jahan',
      description: 'Direct Message',
      icon: '💬',
      type: 'direct',
      isDirect: true,
      participantIds: [currentUserId, 'user_nusrat_jahan'],
      unreadCount: 0,
      lastMessage: 'Photo',
      lastMessageTime: Date.now() - 2 * 3600 * 1000,
      createdAt: Date.now() - 6 * 24 * 3600 * 1000,
    },
    {
      id: `direct_${currentUserId}_user_tanvir_ahmed`,
      name: 'Tanvir Ahmed',
      description: 'Direct Message',
      icon: '💬',
      type: 'direct',
      isDirect: true,
      participantIds: [currentUserId, 'user_tanvir_ahmed'],
      unreadCount: 0,
      lastMessage: 'Voice message • 0:24',
      lastMessageTime: Date.now() - 5 * 3600 * 1000,
      createdAt: Date.now() - 15 * 24 * 3600 * 1000,
    },
  ];
};

export const createDummyMessages = (currentUserId: string): Record<string, ChatMessage[]> => {
  return {
    [`direct_${currentUserId}_user_mira_vibe`]: [
      {
        id: 'msg_mira_1',
        roomId: `direct_${currentUserId}_user_mira_vibe`,
        senderId: 'user_mira_vibe',
        senderName: 'Mira',
        senderAvatar: 'bunny',
        senderCustomAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
        type: 'text',
        content: 'Heyyy! ✨ How is your day going?',
        reactions: {},
        timestamp: Date.now() - 30 * 60 * 1000,
      },
      {
        id: 'msg_mira_2',
        roomId: `direct_${currentUserId}_user_mira_vibe`,
        senderId: currentUserId,
        senderName: 'You',
        senderAvatar: 'falcon',
        type: 'text',
        content: 'Hey Mira! Doing great, working on some design refinements.',
        reactions: {},
        timestamp: Date.now() - 25 * 60 * 1000,
      },
      {
        id: 'msg_mira_3',
        roomId: `direct_${currentUserId}_user_mira_vibe`,
        senderId: 'user_mira_vibe',
        senderName: 'Mira',
        senderAvatar: 'bunny',
        senderCustomAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
        type: 'text',
        content: 'That sounds amazing! Let\'s catch up soon! 🌸',
        reactions: { '🌸': [currentUserId] },
        timestamp: Date.now() - 9 * 60 * 1000,
      },
    ],
    [`direct_${currentUserId}_user_arif_hasan`]: [
      {
        id: 'msg_arif_1',
        roomId: `direct_${currentUserId}_user_arif_hasan`,
        senderId: 'user_arif_hasan',
        senderName: 'Arif Hasan',
        senderAvatar: 'wolf',
        senderCustomAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
        type: 'text',
        content: 'Hey bro! Did you see the new WebRTC audio/video call feature?',
        reactions: {},
        timestamp: Date.now() - 60 * 60 * 1000,
      },
      {
        id: 'msg_arif_2',
        roomId: `direct_${currentUserId}_user_arif_hasan`,
        senderId: currentUserId,
        senderName: 'You',
        senderAvatar: 'falcon',
        type: 'text',
        content: 'Yeah! Works like magic, super clean latency.',
        reactions: {},
        timestamp: Date.now() - 50 * 60 * 1000,
      },
      {
        id: 'msg_arif_3',
        roomId: `direct_${currentUserId}_user_arif_hasan`,
        senderId: 'user_arif_hasan',
        senderName: 'Arif Hasan',
        senderAvatar: 'wolf',
        senderCustomAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
        type: 'text',
        content: 'Let\'s catch up tomorrow! 🔥',
        reactions: { '🔥': [currentUserId] },
        timestamp: Date.now() - 40 * 60 * 1000,
      },
    ],
    [`direct_${currentUserId}_user_nusrat_jahan`]: [
      {
        id: 'msg_nusrat_1',
        roomId: `direct_${currentUserId}_user_nusrat_jahan`,
        senderId: 'user_nusrat_jahan',
        senderName: 'Nusrat Jahan',
        senderAvatar: 'kitten',
        senderCustomAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
        type: 'image',
        content: 'Check out this morning view from Sajek! 🍃',
        attachmentUrl: 'https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=900&auto=format&fit=crop&q=80',
        reactions: { '❤️': [currentUserId] },
        timestamp: Date.now() - 2 * 3600 * 1000,
      },
    ],
    [`direct_${currentUserId}_user_tanvir_ahmed`]: [
      {
        id: 'msg_tanvir_1',
        roomId: `direct_${currentUserId}_user_tanvir_ahmed`,
        senderId: 'user_tanvir_ahmed',
        senderName: 'Tanvir Ahmed',
        senderAvatar: 'falcon',
        senderCustomAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
        type: 'voice',
        content: 'Voice note',
        audioDuration: 24,
        reactions: {},
        timestamp: Date.now() - 5 * 3600 * 1000,
      },
    ],
  };
};
